export const skills = {
  heading: "Skills",
  quote: "Build your skills, not your resume",
  techSkills: [
    "Java",
    "Spring Framework",
    "Spring Boot",
    "RESTful Web Services",
    "Hibernate",
    "JPA",
    "Microservices",
    "SQL",
    "Relational Databases",
    "JavaScript",
    "NodeJS",
    "ReactJS",
    "Redux",
    "HTML",
    "CSS",
    "Bootstrap",
    "Material Design",
    "Git",
    "GitHub",
    "MongoDB",
    "Angular",
  ],
  industryKnowledge: [
    "Software Development",
    "Software Architecture",
    "System Design",
    "SDLC - Software Development Life cycle",
    "Cloud Computing",
    "Backend",
    "Web Development",
  ],
  interpersonalSkills: [
    "Communication",
    "Management",
    "Leadership",
    "Time Management",
    "Teaching",
    "Mentoring",
  ],
};
