export const skills = {
  heading: "Skills",
  quote: "Build your skills, not your resume",
  techSkills: [
    "Java",
    "Spring Framework",
    "Spring Boot",
    "Hibernate",
    "RESTful Web Services",
    "JPA",
    "Microservices",
    "SQL",
    "Relational Databases",
    "JavaScript",
    "NodeJS",
    "ReactJS",
    "Redux",
    "C++",
    "C",
    "Python",
    "HTML",
    "CSS",
    "jQuery",
    "Bootstrap",
    "Material Design",
    "MaterializeCSS",
    "Git",
    "GitHub",
    "MongoDB",
    "Angular",
  ],
  industryKnowledge: [
    "Software",
    "Marketing",
    "Publicity",
    "Blogging",
    "Content Writing",
    "Creative Writing",
    "Web Content",
    "Frontend",
    "Software",
    "Backend",
    "Design",
    "Web",
    "Android",
  ],
  interpersonalSkills: [
    "Communication",
    "Teaching",
    "Time Management",
    "Leadership",
    "Management",
  ],
};
